services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "${APP_PORT}:8000"
    env_file:
      - ./.env
    command: "uvicorn --factory application.api.main:create_app --timeout-graceful-shutdown 2 --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - postgres
    volumes:
      - ./app/:/app/

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - ./.env
    


volumes:
  postgres_data: